### ISSUE TITLE
Arrays getting changed randomly?

### ISSUE THREAD

**Issue by dakotaraymccoy** [enartey/TicTacToe#25]
@skiadas in testModel.spec.js between line 119 and 121 our board.arr property is getting changed from an array of all 0's to an array of all 1's. Do you know what is causing this?

```
    console.log("BEFORE", board.arr);
    it("checkDL() #4", function(){
        console.log("AFTER", board.arr);
```

**Comment by skiadas** [comment]
Your beforeEach runs before each "it". Would that explain it?
